<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TC01_AccountDetailsCheck</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>47b6126a-28db-4996-9c88-e148d0c83f52</testSuiteGuid>
   <testCaseLink>
      <guid>8cb69f47-6af9-436f-bd2f-a7cd4caa3c5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/LoginScreen/TC02_LoginWIthPIN</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b2a762a0-6a7f-4f74-9ac5-aa3cbaa7fcb1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Dashboard/A1. Account Details Screen/A1. Savings Account/TC01_SavingAccount - General SB</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3108ed3-48da-49f6-8051-96f19571de8e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>241affb4-58c9-424f-b16c-c69e3cc1663d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2342c25b-f55f-4a10-ba5b-98761f2216a6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>30d9b55f-19fc-4b85-8afb-3e53dfed9c84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Dashboard/A1. Account Details Screen/A1. Savings Account/TC02_SavingAccount - High Value</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d95f2ccf-eb96-4e78-b977-6d553e1e5bed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cad79b7-a46c-4e42-8c83-fb62da3af294</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>692db240-b9ae-4d96-aeea-004687698786</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3af2c83c-9ad1-4968-931e-2a0f631ac81b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Dashboard/A1. Account Details Screen/B1. Credit Card/TC01_CreditCard - AMEX AGORA</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf7fb679-45a3-4c36-918e-c55d08a2d328</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7b9f2b5-a527-4456-bcfe-97538ff805d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a090ce24-d75c-412b-b7d2-137287e0ce3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccedcec7-8357-4a59-81e1-77ef30697e4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87ffa762-a7e4-41c0-9696-135c90d52a7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b8f70d5-4d08-4acf-90da-e6671dc2d027</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Dashboard/A1. Account Details Screen/B1. Credit Card/TC02_CreditCard - AMEX</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60220010-6250-4bd5-a553-f27a53e3e98f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8faeb67-da61-4a3e-9933-8db2ce31a7bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>650f71c5-775d-4d64-a29b-c331bcad3da5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d18daae0-2295-4c57-bd7f-1f4b2ad12926</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07c7c33e-8607-42ec-9c0e-d07e97b21949</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4cc219ba-7354-433b-8525-5e61bde86d4c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Dashboard/A1. Account Details Screen/C1. Prepaid Card/TC01_PrepaidCard - Master</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c32553fa-4f9f-4afc-8d2f-2a3ce202f003</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a40b1831-8b10-4de5-91ea-a0c6947e6374</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46fad231-503a-412d-8f2a-35406fcc6d85</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f0c8e5d-6417-4516-a64e-5e26737ebf01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c2e465a-25a1-4a60-ac6a-f80e1d714466</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
