<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Transfer Between City Bank Accounts</description>
   <name>TS01 - FixedDeposit</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>458d6d49-e45e-4127-8fa1-e3b79e0de124</testSuiteGuid>
   <testCaseLink>
      <guid>fa06d8c9-3510-4aec-8118-ad958debfbb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/AccountsScreen/TC02_AccountDetailsStore</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6bdf9390-9309-46af-9f6f-615ca2d5e227</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/MoreScreen/TC01_Navigate_More_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d08b4e64-1861-4d5a-85a4-e7f3b61c7a5c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/MoreScreen/B1. Account Services/TC01_Navigate_Account_Services_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>911ffa20-e65e-4c2f-8b9a-ec56061d6abb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/MoreScreen/B1. Account Services/A1. FixedDeposit/TC00_Navigate_Fixed_Deposit_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c84d4cc8-43bd-40e8-b5ee-31a742b55566</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/MoreScreen/B1. Account Services/A1. FixedDeposit/TC01_FixedDeposit - General</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5762ba7-1dd4-47d7-a8e0-77c1f02160a7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b0d8dee-b33e-4a10-a9f9-7deede3b9a16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/MoreScreen/B1. Account Services/A1. FixedDeposit/TC02_FixedDeposit_OTP_Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d039800-7243-4728-9620-847c3fad66cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d1eb4b5-cecf-4027-8fa1-d3e0c6b4fb13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a54444f8-3798-49a1-8d93-8152907f414e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f736906-8e6f-45df-8e58-b2764e71ff5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c84d27bb-1ef2-495b-9638-01dd83d96ea5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>47e04491-68fc-4dfb-8bb2-26f80a32838d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23790c88-9ad2-47e3-86f5-50d1ae0cd8a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd4e23e5-7f73-4902-88bc-9b8d5283fdc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0675050c-15f6-486a-8393-48e05402f11e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bed43a5-38a8-41d6-b12b-e6f1fe74ea63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/MoreScreen/B1. Account Services/A1. FixedDeposit/TC03_RequestSuccessScreen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13384b1c-d180-4d01-86c3-da59cd7e11f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27608300-0bb4-402d-aa70-f88812c22051</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/MoreScreen/B1. Account Services/A1. FixedDeposit/TC04_CheckAccountDetailsAdjustment</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
