<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Transfer Between City Bank Accounts</description>
   <name>TS01 - CityBankAccount - City Account</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>0c501f21-77ea-492a-acdd-51e2f7e83895</testSuiteGuid>
   <testCaseLink>
      <guid>9a90af4e-5b3f-4b7f-b749-efbb5721160e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/LoginScreen/TC02_LoginWIthPIN</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fa06d8c9-3510-4aec-8118-ad958debfbb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/AccountsScreen/TC02_AccountDetailsStore</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6bdf9390-9309-46af-9f6f-615ca2d5e227</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/TransferScreen/TC01_Navigate_Transfer_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3cc9d302-7a04-457d-a285-07f0cb62fcf5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/TransferScreen/A1. CityBankAccount/TC01_Navigate_CityBank_Account_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>04b563db-26de-4cb0-bcb5-6d092fb37a36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/iOS/TransferScreen/A1. CityBankAccount/B2. CityAccTransfer/TC01_CityAccountTransfer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85c312d7-46a8-4197-b70b-19add0c6b8a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee32fcc1-5919-40d8-9757-fcb40e1c368a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>026de206-2395-43c7-83f9-d8e3212427b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d083c44a-88e4-4bc8-8b36-40f36e65b540</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17f47c19-b6a5-44cb-bad8-ca37ce78edba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60cad2dc-b4b7-4942-875f-b1c1ae9e03f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f70e033-23c7-4904-b048-f5dc2980e469</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02d50802-9f87-437f-a379-5091709e381e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>034a31b5-9f33-4595-bc68-09deca47bc73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC04_NavigateTo_AddBeneficiary_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>0dc5bbc7-97e8-4d92-ac97-1917daab5937</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/B1. City Bank Account Transfer/TC01_City Bank Transfer - Add Beneficiary</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98a38de6-d384-4b14-8d62-9abd94b104ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6af37b1-acd8-4380-b9a2-8bbe104f57da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d54f80ea-d582-4a09-8a4c-bf51671bc426</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71c3b59e-656c-4b37-a488-cdef942218ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d85d7f3-eaac-4f65-9fc4-75b6e097d64e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6598dc8a-fa97-4f70-bec1-a8b4630f0fd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de3c9a1f-f7c5-45ff-b862-e0cd81f9ed1e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f65f4aba-3a4f-4a5d-b496-c6f36034733a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC01_CityTouch Security Verification</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>852178df-4526-47d7-b2c0-7108b81935b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e416303b-6f47-46d9-8dab-7220bfbf8bc2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/TC01_Navigate_CityBank_Account_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>de5ae806-2db7-441e-8cbf-bd1419869f12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/B2. CityAccTransfer/TC01_CityAccountTransfer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98a38de6-d384-4b14-8d62-9abd94b104ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6af37b1-acd8-4380-b9a2-8bbe104f57da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d54f80ea-d582-4a09-8a4c-bf51671bc426</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71c3b59e-656c-4b37-a488-cdef942218ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d85d7f3-eaac-4f65-9fc4-75b6e097d64e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6598dc8a-fa97-4f70-bec1-a8b4630f0fd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de3c9a1f-f7c5-45ff-b862-e0cd81f9ed1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf6d5dcb-3176-43d5-a364-d33d0a98cdf7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bed43a5-38a8-41d6-b12b-e6f1fe74ea63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/B2. CityAccTransfer/TC02_CityAccFundTransfer_OTP_Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc972036-03b7-41ab-aac4-32299def4685</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>870d87e5-63d5-4b22-a915-79b0014ed32c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/B2. CityAccTransfer/TC03_CityAccFundTransfer_SuccessScreen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6cbec292-2651-41e5-b518-384d2c470cc5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/B2. CityAccTransfer/TC04_CheckAccountDetailsAdjustment</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>07563a47-803a-4b4b-89c2-9282b9715a08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/TC01_Navigate_Transfer_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4189c292-67ed-4059-b789-276f3b3e65e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC03_NavigateTo_Beneficiary_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bff591c3-a210-4013-ad7e-79f181dac425</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/B1. City Bank Account Transfer/TC02_City Bank Transfer - Delete Beneficiary</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>95344ac4-c311-4e41-9294-68adde9a45e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/B1. City Bank Account Transfer/TC02_City Bank Transfer - Delete Beneficiary</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
