<<<<<<< Upstream, based on branch 'master' of http://172.16.229.231:8084/moshiurpiash/Citytouch_Automation_Testing.git
<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS01_AddBeneficiary</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e1d133f8-aeca-42bf-b159-fa7ea25141a7</testSuiteGuid>
   <testCaseLink>
      <guid>2fd8771a-1892-4476-9605-c46599b81a31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/LoginScreen/TC02_LoginWIthPIN</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4c64cf79-1c16-4a5c-b122-c5131280a612</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/TC01_Navigate_Payment_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d02a068e-3e8c-4c7c-86b8-4a3c79724c73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC06_NavigateTo_PaymentBenificiery_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6de49cff-6c52-465e-8623-b5eabd50e3cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC04_NavigateTo_AddBeneficiary_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3ba0efa1-cf24-4dab-a0d9-8901a4f90172</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/G1. Other Credit Card Payment/TC01_Credit_Card_Payment - Add Beneficiary</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70c9f641-9a54-4632-ab21-4401a447130d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab26bd6c-da36-4531-b995-4913d6e8c2fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13d724f4-a338-41a3-9375-52e36aa89eff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e72cb71-cc3c-4100-a015-9450739eb95b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80a4b2bb-b9fd-43d4-b4e7-686cf20acb00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89d1032c-59f6-483c-b0bb-b501801d1e5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf3069db-e86a-4a73-b3ac-a9b3ce5430fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d12f8cf3-93b8-4f62-9acf-d4300e4983b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC01_CityTouch Security Verification</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>852178df-4526-47d7-b2c0-7108b81935b2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
=======
<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS01_AddBeneficiary</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e1d133f8-aeca-42bf-b159-fa7ea25141a7</testSuiteGuid>
   <testCaseLink>
      <guid>2fd8771a-1892-4476-9605-c46599b81a31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/LoginScreen/TC02_LoginWIthPIN</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4c64cf79-1c16-4a5c-b122-c5131280a612</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/TC01_Navigate_Payment_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6de49cff-6c52-465e-8623-b5eabd50e3cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC04_NavigateTo_AddBeneficiary_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3ba0efa1-cf24-4dab-a0d9-8901a4f90172</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/G1. Other Credit Card Payment/TC01_Credit_Card_Payment - Add Beneficiary</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70c9f641-9a54-4632-ab21-4401a447130d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab26bd6c-da36-4531-b995-4913d6e8c2fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13d724f4-a338-41a3-9375-52e36aa89eff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e72cb71-cc3c-4100-a015-9450739eb95b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80a4b2bb-b9fd-43d4-b4e7-686cf20acb00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89d1032c-59f6-483c-b0bb-b501801d1e5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf3069db-e86a-4a73-b3ac-a9b3ce5430fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d12f8cf3-93b8-4f62-9acf-d4300e4983b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC01_CityTouch Security Verification</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>852178df-4526-47d7-b2c0-7108b81935b2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
>>>>>>> 5fa4c80 Project Setup for iOS
