<<<<<<< Upstream, based on branch 'master' of http://172.16.229.231:8084/moshiurpiash/Citytouch_Automation_Testing.git
<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Transfer Between City Bank Accounts</description>
   <name>TS01 - bKashTransfer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b751e055-b991-453c-81b6-76abd0402849</testSuiteGuid>
   <testCaseLink>
      <guid>a252a49a-41f2-4ef4-958a-cd5bfeb8ced3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/LoginScreen/TC02_LoginWIthPIN</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fa06d8c9-3510-4aec-8118-ad958debfbb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/AccountsScreen/TC02_AccountDetailsStore</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6bdf9390-9309-46af-9f6f-615ca2d5e227</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/TC01_Navigate_Transfer_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c84d4cc8-43bd-40e8-b5ee-31a742b55566</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/E1. bKashTransfer/TC01_bKashTransfer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e4e3e27-5587-4fe9-a2ca-25790c68ec43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dc81e48-6c15-492e-ac18-467be321a78f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a56dc93-12ab-4845-b578-598ac47cc31f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0d08ca2-c867-451e-954d-f09804af89a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33c29e5a-c5d1-4b5e-b388-9fc74cd4b094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b71c402d-e293-4081-bce1-b2938ab2b313</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d2bd654-30fc-4141-89b9-4badf43fb44b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d203322a-1682-4f2f-a471-94586489816c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27bfe1ef-e87a-4016-8d63-185454fe04d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/E1. bKashTransfer/TC01_bKashTransfer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e4e3e27-5587-4fe9-a2ca-25790c68ec43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dc81e48-6c15-492e-ac18-467be321a78f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a56dc93-12ab-4845-b578-598ac47cc31f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0d08ca2-c867-451e-954d-f09804af89a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33c29e5a-c5d1-4b5e-b388-9fc74cd4b094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b71c402d-e293-4081-bce1-b2938ab2b313</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d2bd654-30fc-4141-89b9-4badf43fb44b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d203322a-1682-4f2f-a471-94586489816c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f65f4aba-3a4f-4a5d-b496-c6f36034733a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC01_CityTouch Security Verification</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>852178df-4526-47d7-b2c0-7108b81935b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e416303b-6f47-46d9-8dab-7220bfbf8bc2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/TC01_Navigate_CityBank_Account_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>de5ae806-2db7-441e-8cbf-bd1419869f12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/B2. CityAccTransfer/TC01_CityAccountTransfer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98a38de6-d384-4b14-8d62-9abd94b104ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6af37b1-acd8-4380-b9a2-8bbe104f57da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d54f80ea-d582-4a09-8a4c-bf51671bc426</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71c3b59e-656c-4b37-a488-cdef942218ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d85d7f3-eaac-4f65-9fc4-75b6e097d64e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6598dc8a-fa97-4f70-bec1-a8b4630f0fd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de3c9a1f-f7c5-45ff-b862-e0cd81f9ed1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf6d5dcb-3176-43d5-a364-d33d0a98cdf7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bed43a5-38a8-41d6-b12b-e6f1fe74ea63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/B2. CityAccTransfer/TC02_CityAccFundTransfer_OTP_Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc972036-03b7-41ab-aac4-32299def4685</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>870d87e5-63d5-4b22-a915-79b0014ed32c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/B2. CityAccTransfer/TC03_CityAccFundTransfer_SuccessScreen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6cbec292-2651-41e5-b518-384d2c470cc5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/B2. CityAccTransfer/TC04_CheckAccountDetailsAdjustment</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>07563a47-803a-4b4b-89c2-9282b9715a08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/TC01_Navigate_Transfer_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4189c292-67ed-4059-b789-276f3b3e65e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC03_NavigateTo_Beneficiary_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bff591c3-a210-4013-ad7e-79f181dac425</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/B1. City Bank Account Transfer/TC02_City Bank Transfer - Delete Beneficiary</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>95344ac4-c311-4e41-9294-68adde9a45e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/B1. City Bank Account Transfer/TC02_City Bank Transfer - Delete Beneficiary</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>830242e9-6fdc-476f-a200-863b401f81f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/LogoutScreen/TC02_Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
=======
<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Transfer Between City Bank Accounts</description>
   <name>TS01 - bKashTransfer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b751e055-b991-453c-81b6-76abd0402849</testSuiteGuid>
   <testCaseLink>
      <guid>a252a49a-41f2-4ef4-958a-cd5bfeb8ced3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/LoginScreen/TC02_LoginWIthPIN</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fa06d8c9-3510-4aec-8118-ad958debfbb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/AccountsScreen/TC02_AccountDetailsStore</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6bdf9390-9309-46af-9f6f-615ca2d5e227</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/TC01_Navigate_Transfer_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c84d4cc8-43bd-40e8-b5ee-31a742b55566</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/E1. bKashTransfer/TC01_bKashTransfer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e4e3e27-5587-4fe9-a2ca-25790c68ec43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dc81e48-6c15-492e-ac18-467be321a78f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a56dc93-12ab-4845-b578-598ac47cc31f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0d08ca2-c867-451e-954d-f09804af89a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33c29e5a-c5d1-4b5e-b388-9fc74cd4b094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b71c402d-e293-4081-bce1-b2938ab2b313</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d2bd654-30fc-4141-89b9-4badf43fb44b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d203322a-1682-4f2f-a471-94586489816c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>27bfe1ef-e87a-4016-8d63-185454fe04d9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/E1. bKashTransfer/TC01_bKashTransfer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e4e3e27-5587-4fe9-a2ca-25790c68ec43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0dc81e48-6c15-492e-ac18-467be321a78f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a56dc93-12ab-4845-b578-598ac47cc31f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0d08ca2-c867-451e-954d-f09804af89a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33c29e5a-c5d1-4b5e-b388-9fc74cd4b094</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b71c402d-e293-4081-bce1-b2938ab2b313</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d2bd654-30fc-4141-89b9-4badf43fb44b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d203322a-1682-4f2f-a471-94586489816c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f65f4aba-3a4f-4a5d-b496-c6f36034733a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC01_CityTouch Security Verification</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>852178df-4526-47d7-b2c0-7108b81935b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e416303b-6f47-46d9-8dab-7220bfbf8bc2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/TC01_Navigate_CityBank_Account_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>de5ae806-2db7-441e-8cbf-bd1419869f12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/B2. CityAccTransfer/TC01_CityAccountTransfer</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98a38de6-d384-4b14-8d62-9abd94b104ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6af37b1-acd8-4380-b9a2-8bbe104f57da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d54f80ea-d582-4a09-8a4c-bf51671bc426</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71c3b59e-656c-4b37-a488-cdef942218ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d85d7f3-eaac-4f65-9fc4-75b6e097d64e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6598dc8a-fa97-4f70-bec1-a8b4630f0fd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de3c9a1f-f7c5-45ff-b862-e0cd81f9ed1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf6d5dcb-3176-43d5-a364-d33d0a98cdf7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bed43a5-38a8-41d6-b12b-e6f1fe74ea63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/B2. CityAccTransfer/TC02_CityAccFundTransfer_OTP_Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc972036-03b7-41ab-aac4-32299def4685</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>870d87e5-63d5-4b22-a915-79b0014ed32c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/B2. CityAccTransfer/TC03_CityAccFundTransfer_SuccessScreen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6cbec292-2651-41e5-b518-384d2c470cc5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/A1. CityBankAccount/B2. CityAccTransfer/TC04_CheckAccountDetailsAdjustment</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>07563a47-803a-4b4b-89c2-9282b9715a08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/TransferScreen/TC01_Navigate_Transfer_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4189c292-67ed-4059-b789-276f3b3e65e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC03_NavigateTo_Beneficiary_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bff591c3-a210-4013-ad7e-79f181dac425</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/B1. City Bank Account Transfer/TC02_City Bank Transfer - Delete Beneficiary</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2c6c098-39b0-4470-8fe8-df37c5520582</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ec3412d-3be1-4deb-aa8d-d1226d0f7688</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cd6fa9a-285b-45c5-bac8-988554488b5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4458b01-2683-4a47-a71c-07b4e8602e91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a00f43a-d124-4b83-adac-a8755f6512e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>411acb71-1f22-4cf1-a37a-7ada4e330acb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7344da32-cb2d-49e1-98c7-438aacf2ac18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>95344ac4-c311-4e41-9294-68adde9a45e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/B1. City Bank Account Transfer/TC02_City Bank Transfer - Delete Beneficiary</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2c6c098-39b0-4470-8fe8-df37c5520582</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ec3412d-3be1-4deb-aa8d-d1226d0f7688</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cd6fa9a-285b-45c5-bac8-988554488b5c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4458b01-2683-4a47-a71c-07b4e8602e91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a00f43a-d124-4b83-adac-a8755f6512e5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>411acb71-1f22-4cf1-a37a-7ada4e330acb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7344da32-cb2d-49e1-98c7-438aacf2ac18</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>830242e9-6fdc-476f-a200-863b401f81f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/LogoutScreen/TC02_Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
>>>>>>> 5fa4c80 Project Setup for iOS
