<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS01_VISAInstantPayment</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4e921b3c-c18b-45f2-8f20-a37fe1c833bb</testSuiteGuid>
   <testCaseLink>
      <guid>ccb98169-9982-4f55-aa4f-02e229a8cbba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/LoginScreen/TC02_LoginWIthPIN</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>90c4f303-3c73-461e-9845-c18a52c19613</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/AccountsScreen/TC02_AccountDetailsStore</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e7b969df-91df-42cf-b174-75df31aad7fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/TC01_Navigate_Payment_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2e7007fc-f887-4633-bb03-07a2ed546070</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/C1. Visa Instant Payment/TC01_VisaInstantPayment</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ff6b611f-9b58-4e75-901b-5b5c25abb073</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/C1. Visa Instant Payment/TC02_VisaInstantPayment_OTP_Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b5bce0e-974f-46a0-8077-ee62e78fe8a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d34df3b-514b-4f1e-9db1-9e536435c5ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2f9cf45-9d25-45ad-97f7-35c167cd2350</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f271cc07-6859-4304-9ced-f9e20954278f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc5e7a95-5b17-4331-8318-40a191fb93f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>db364840-2dd6-4188-996b-2c86f7b1314f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/C1. Visa Instant Payment/TC03_VisaInstantPayment_SuccessScreen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3ed3d1a4-7ff8-4f68-88cc-3f753bf6ae06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/C1. Visa Instant Payment/TC04_CheckAccountDetailsAdjustment</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
=======
<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS01_VISAInstantPayment</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>4e921b3c-c18b-45f2-8f20-a37fe1c833bb</testSuiteGuid>
   <testCaseLink>
      <guid>ccb98169-9982-4f55-aa4f-02e229a8cbba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/LoginScreen/TC02_LoginWIthPIN</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>90c4f303-3c73-461e-9845-c18a52c19613</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/AccountsScreen/TC02_AccountDetailsStore</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>48720c03-3426-4dd8-bf9a-1cb7e935524b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/TC01_Navigate_Payment_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9ddf9944-398e-479d-b66c-d29216297737</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC06_NavigateTo_PaymentBenificiery_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a4329975-2e35-4201-a4d3-94e5424ae306</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC04_NavigateTo_AddBeneficiary_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>003d5b14-09bc-42b7-8f81-d4c0068d61b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/H1. VisaInstantPayment/TC01_Visa_Instant_Payment - Add Beneficiary</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bb291f7-d106-417d-b6b5-0aca5464a45a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ead4dbf4-a966-4ee0-95e2-1d3a058b9e75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d5d42b9-cd6f-4f43-a242-4ca2ef946c2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4359c6c7-6d79-499c-983e-7092edf5b164</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fc1ac18-e5a7-404a-bb22-ba42d95d3f36</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f1df9d52-00ac-45b1-a325-2abc4d73ac3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC01_CityTouch Security Verification</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>852178df-4526-47d7-b2c0-7108b81935b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7b969df-91df-42cf-b174-75df31aad7fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/TC01_Navigate_Payment_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>2e7007fc-f887-4633-bb03-07a2ed546070</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/C1. Visa Instant Payment/TC01_VisaInstantPayment</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ff6b611f-9b58-4e75-901b-5b5c25abb073</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/C1. Visa Instant Payment/TC02_VisaInstantPayment_OTP_Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b5bce0e-974f-46a0-8077-ee62e78fe8a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d34df3b-514b-4f1e-9db1-9e536435c5ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2f9cf45-9d25-45ad-97f7-35c167cd2350</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f271cc07-6859-4304-9ced-f9e20954278f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc5e7a95-5b17-4331-8318-40a191fb93f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>db364840-2dd6-4188-996b-2c86f7b1314f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/C1. Visa Instant Payment/TC03_VisaInstantPayment_SuccessScreen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3ed3d1a4-7ff8-4f68-88cc-3f753bf6ae06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/C1. Visa Instant Payment/TC04_CheckAccountDetailsAdjustment</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
>>>>>>> origin/Eftiar
