<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Transfer Between City Bank Accounts</description>
   <name>TS01 - CreditCardPayment - Other Account</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>68db26a3-8a11-4a7c-8bd0-fd48f0c758c6</testSuiteGuid>
   <testCaseLink>
      <guid>a252a49a-41f2-4ef4-958a-cd5bfeb8ced3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/LoginScreen/TC02_LoginWIthPIN</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>fa06d8c9-3510-4aec-8118-ad958debfbb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/AccountsScreen/TC02_AccountDetailsStore</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6bdf9390-9309-46af-9f6f-615ca2d5e227</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/TC01_Navigate_Payment_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3cc9d302-7a04-457d-a285-07f0cb62fcf5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/B1. CreditCardPayment/TC01_Navigate_CreditCardPayment</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>04b563db-26de-4cb0-bcb5-6d092fb37a36</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/B1. CreditCardPayment/B2. OtherCreditCardPayment/TC01_OtherCreditCardPayment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88cf050a-39c7-40d2-a66b-9e0aea903a33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b528ac1-a76c-46be-ae55-53ccbcb65648</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>351f8636-7a79-4485-a42a-832b2eea698b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ef87d24-9fab-4395-b4dd-1ad9d1f6b1b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd4a5691-c6c2-4b51-b5fc-1be23c15b332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>355a73ce-3945-4df3-872d-cd832415598f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b317a0d-9144-443a-baf9-cbede418b62c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d7fd507-4860-4517-a4b5-c635d98a0e9e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5819273d-e02c-4f20-9eb0-92fdd306e6e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/B1. CreditCardPayment/B2. OtherCreditCardPayment/TC01_OtherCreditCardPayment</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88cf050a-39c7-40d2-a66b-9e0aea903a33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b528ac1-a76c-46be-ae55-53ccbcb65648</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>351f8636-7a79-4485-a42a-832b2eea698b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ef87d24-9fab-4395-b4dd-1ad9d1f6b1b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd4a5691-c6c2-4b51-b5fc-1be23c15b332</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>355a73ce-3945-4df3-872d-cd832415598f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b317a0d-9144-443a-baf9-cbede418b62c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d7fd507-4860-4517-a4b5-c635d98a0e9e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bed43a5-38a8-41d6-b12b-e6f1fe74ea63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/B1. CreditCardPayment/B2. OtherCreditCardPayment/TC02_OtherCreditCardPayment_OTP_Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a36687ec-a610-47d2-8035-9c347a6f6368</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c46122b6-d8e0-49ae-a19a-45e59cf8d031</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e0298bb-af4c-480a-901f-44eb25da8a90</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>870d87e5-63d5-4b22-a915-79b0014ed32c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/B1. CreditCardPayment/B2. OtherCreditCardPayment/TC03_OtherCreditCardPayment_SuccessScreen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6cbec292-2651-41e5-b518-384d2c470cc5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/B1. CreditCardPayment/B2. OtherCreditCardPayment/TC04_CheckAccountDetailsAdjustment</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>dcc6a090-395c-436e-b983-a1c2c74b7add</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/PaymentScreen/TC01_Navigate_Payment_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>4189c292-67ed-4059-b789-276f3b3e65e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/TC03_NavigateTo_Beneficiary_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bff591c3-a210-4013-ad7e-79f181dac425</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/Beneficiary/G1. Other Credit Card Payment/TC02_Credit_Card_Payment - Delete Beneficiary</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a37593d-facb-4e3f-af0a-e851f78f28fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2526690f-51fc-498d-946c-04275683703a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cfa9ee6-fbcd-45c2-be9c-873728edef0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b3801f6-9140-4f4b-a4a3-4a513c9c8a03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46c2ba6f-18fd-4f6d-abcb-119564aedf7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c7d5262-d134-4fff-b4d4-8ef1c510db75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15e2260d-af44-4277-a087-026d8393c0bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>830242e9-6fdc-476f-a200-863b401f81f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/LogoutScreen/TC02_Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
