<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Transfer Between City Bank Accounts</description>
   <name>TS01 - DebitCardActivate</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b9462f53-e3b0-44b2-b6e2-ee32608be503</testSuiteGuid>
   <testCaseLink>
      <guid>6bdf9390-9309-46af-9f6f-615ca2d5e227</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/MoreScreen/TC01_Navigate_More_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b2acc80d-0f8b-4662-9ab3-96b617d5f648</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/MoreScreen/C1. Card Services/TC01_Navigate_Card_Services_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d08b4e64-1861-4d5a-85a4-e7f3b61c7a5c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/MoreScreen/C1. Card Services/B1. Activate Debit Card/TC00_Navigate_Activate_Debit_Card_Screen</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>911ffa20-e65e-4c2f-8b9a-ec56061d6abb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/MoreScreen/C1. Card Services/B1. Activate Debit Card/TC01_ActiveDebitCard</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9fb6ce0e-01da-45d6-9bc1-3a58cd2d53db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>657f9ebd-b304-445c-8dc8-5ac40740d296</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b940da7-0c78-408d-b6fc-18c5766ca219</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>999fb925-3273-4e90-9626-0f7f8a6f31e8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b0d8dee-b33e-4a10-a9f9-7deede3b9a16</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/MoreScreen/C1. Card Services/B1. Activate Debit Card/TC02_ActiveDebitCard_OTP_Screen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>616cec24-8a84-4019-a274-ead75087d4e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>010c51f7-6208-4dce-b581-0938528d1107</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>981277a1-3585-4130-8567-8ffe2d2942fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a868bab-b060-4882-802c-6d8a1b1e4c9e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bed43a5-38a8-41d6-b12b-e6f1fe74ea63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Android/MoreScreen/C1. Card Services/B1. Activate Debit Card/TC03_RequestSuccessScreen</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9e56934-3439-40c3-a3d5-e0ffc90c049e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
